UI for create category
pittalamadhuri/money-man pull request #3
Opened 2021-12-20 12:01 UTC by pittalamadhuri

2021-12-30 07:30 UTC, saiumesh535 commented on src/components/Select/SelectComponent.tsx
>      function handleChange(e: any){
avoid any

2021-12-30 07:30 UTC, saiumesh535 commented on src/components/TextComponent/TextComponent.tsx
> +        <TextField
Indentation

2021-12-30 07:30 UTC, saiumesh535 commented on src/components/TextComponent/TextComponent.tsx
> +    handler: (target: any, formElement: string| undefined) => void;
avoid any

2021-12-30 07:30 UTC, saiumesh535 commented on src/data/sagas.ts
> +        console.error("Error in saga");
handle errors and show to user

2021-12-30 07:31 UTC, saiumesh535 requested changes
Requested changes

2021-12-30 08:15 UTC, pittalamadhuri commented on src/data/sagas.ts
> +        console.error("Error in saga");
Will do later as snackbar

2021-12-31 14:47 UTC, saiumesh535 commented on src/components/ButtonComponent/ButtonComponent.scss
> +Button {
avoid HTML element to change style rather use a class

2021-12-31 14:48 UTC, saiumesh535 commented on src/pages/Category/CreateCategory.tsx
> +                        {categories && categories.map(category => {
categories?.map

2021-12-31 14:48 UTC, saiumesh535 approved these changes
LGTM!

2022-01-01 05:57 UTC, merged